<?php

namespace App\Http\Controllers\Im;

use App\Http\Controllers\Controller;

class RpcController extends Controller
{
    public function getMiddleware()
    {
        \Log::info('rpc:' . var_export(parent::getMiddleware(), true));

        return parent::getMiddleware(); // TODO: Change the autogenerated stub
    }

    public function rpc()
    {
        \Log::info('rpc:' . var_export($this->request->all(), true));

        return $this->success();
    }
}
